//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWebCuponSystemService.CuponServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CuponServiceReference.BussinessServicesSoap")]
    public interface BussinessServicesSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessResponse AddBussiness(UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessResponse> AddBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessResponse DeleteBussiness(UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessResponse> DeleteBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApproveBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessResponse ApproveBussiness(UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApproveBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessResponse> ApproveBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessResponse UpdateBussiness(UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessResponse> UpdateBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByName", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameResponse FindBussinessByName(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByName", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameResponse> FindBussinessByNameAsync(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequest request);
        
        // CODEGEN: Generating message contract since element name ownerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessOfOwner", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerResponse FindBussinessOfOwner(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessOfOwner", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerResponse> FindBussinessOfOwnerAsync(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByCategory", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryResponse FindBussinessByCategory(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryResponse> FindBussinessByCategoryAsync(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUnapprovedBussinessResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUnapprovedBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessResponse GetAllUnapprovedBussiness(UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUnapprovedBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessResponse> GetAllUnapprovedBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequestBody Body;
        
        public AddBussinessRequest() {
        }
        
        public AddBussinessRequest(UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string longtitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string photo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string bussinessOwnerId;
        
        public AddBussinessRequestBody() {
        }
        
        public AddBussinessRequestBody(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            this.name = name;
            this.description = description;
            this.category = category;
            this.latitude = latitude;
            this.longtitude = longtitude;
            this.photo = photo;
            this.bussinessOwnerId = bussinessOwnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessResponseBody Body;
        
        public AddBussinessResponse() {
        }
        
        public AddBussinessResponse(UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddBussinessResult;
        
        public AddBussinessResponseBody() {
        }
        
        public AddBussinessResponseBody(bool AddBussinessResult) {
            this.AddBussinessResult = AddBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequestBody Body;
        
        public DeleteBussinessRequest() {
        }
        
        public DeleteBussinessRequest(UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessId;
        
        public DeleteBussinessRequestBody() {
        }
        
        public DeleteBussinessRequestBody(string bussinessId) {
            this.bussinessId = bussinessId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessResponseBody Body;
        
        public DeleteBussinessResponse() {
        }
        
        public DeleteBussinessResponse(UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteBussinessResult;
        
        public DeleteBussinessResponseBody() {
        }
        
        public DeleteBussinessResponseBody(bool DeleteBussinessResult) {
            this.DeleteBussinessResult = DeleteBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequestBody Body;
        
        public ApproveBussinessRequest() {
        }
        
        public ApproveBussinessRequest(UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessId;
        
        public ApproveBussinessRequestBody() {
        }
        
        public ApproveBussinessRequestBody(string bussinessId) {
            this.bussinessId = bussinessId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessResponseBody Body;
        
        public ApproveBussinessResponse() {
        }
        
        public ApproveBussinessResponse(UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ApproveBussinessResult;
        
        public ApproveBussinessResponseBody() {
        }
        
        public ApproveBussinessResponseBody(bool ApproveBussinessResult) {
            this.ApproveBussinessResult = ApproveBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequestBody Body;
        
        public UpdateBussinessRequest() {
        }
        
        public UpdateBussinessRequest(UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string longtitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string photo;
        
        public UpdateBussinessRequestBody() {
        }
        
        public UpdateBussinessRequestBody(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            this.bussinessId = bussinessId;
            this.name = name;
            this.description = description;
            this.category = category;
            this.latitude = latitude;
            this.longtitude = longtitude;
            this.photo = photo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessResponseBody Body;
        
        public UpdateBussinessResponse() {
        }
        
        public UpdateBussinessResponse(UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateBussinessResult;
        
        public UpdateBussinessResponseBody() {
        }
        
        public UpdateBussinessResponseBody(bool UpdateBussinessResult) {
            this.UpdateBussinessResult = UpdateBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByName", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequestBody Body;
        
        public FindBussinessByNameRequest() {
        }
        
        public FindBussinessByNameRequest(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessName;
        
        public FindBussinessByNameRequestBody() {
        }
        
        public FindBussinessByNameRequestBody(string bussinessName) {
            this.bussinessName = bussinessName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameResponseBody Body;
        
        public FindBussinessByNameResponse() {
        }
        
        public FindBussinessByNameResponse(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessByNameResult;
        
        public FindBussinessByNameResponseBody() {
        }
        
        public FindBussinessByNameResponseBody(string FindBussinessByNameResult) {
            this.FindBussinessByNameResult = FindBussinessByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessOfOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessOfOwner", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequestBody Body;
        
        public FindBussinessOfOwnerRequest() {
        }
        
        public FindBussinessOfOwnerRequest(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessOfOwnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ownerID;
        
        public FindBussinessOfOwnerRequestBody() {
        }
        
        public FindBussinessOfOwnerRequestBody(string ownerID) {
            this.ownerID = ownerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessOfOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessOfOwnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerResponseBody Body;
        
        public FindBussinessOfOwnerResponse() {
        }
        
        public FindBussinessOfOwnerResponse(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessOfOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessOfOwnerResult;
        
        public FindBussinessOfOwnerResponseBody() {
        }
        
        public FindBussinessOfOwnerResponseBody(string FindBussinessOfOwnerResult) {
            this.FindBussinessOfOwnerResult = FindBussinessOfOwnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByCategory", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequestBody Body;
        
        public FindBussinessByCategoryRequest() {
        }
        
        public FindBussinessByCategoryRequest(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public FindBussinessByCategoryRequestBody() {
        }
        
        public FindBussinessByCategoryRequestBody(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryResponseBody Body;
        
        public FindBussinessByCategoryResponse() {
        }
        
        public FindBussinessByCategoryResponse(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessByCategoryResult;
        
        public FindBussinessByCategoryResponseBody() {
        }
        
        public FindBussinessByCategoryResponseBody(string FindBussinessByCategoryResult) {
            this.FindBussinessByCategoryResult = FindBussinessByCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUnapprovedBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUnapprovedBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequestBody Body;
        
        public GetAllUnapprovedBussinessRequest() {
        }
        
        public GetAllUnapprovedBussinessRequest(UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUnapprovedBussinessRequestBody {
        
        public GetAllUnapprovedBussinessRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUnapprovedBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUnapprovedBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessResponseBody Body;
        
        public GetAllUnapprovedBussinessResponse() {
        }
        
        public GetAllUnapprovedBussinessResponse(UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUnapprovedBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllUnapprovedBussinessResult;
        
        public GetAllUnapprovedBussinessResponseBody() {
        }
        
        public GetAllUnapprovedBussinessResponseBody(string GetAllUnapprovedBussinessResult) {
            this.GetAllUnapprovedBussinessResult = GetAllUnapprovedBussinessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BussinessServicesSoapChannel : UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BussinessServicesSoapClient : System.ServiceModel.ClientBase<UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap>, UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap {
        
        public BussinessServicesSoapClient() {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BussinessServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessResponse UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.AddBussiness(UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequest request) {
            return base.Channel.AddBussiness(request);
        }
        
        public bool AddBussiness(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            inValue.Body.bussinessOwnerId = bussinessOwnerId;
            UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessResponse retVal = ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).AddBussiness(inValue);
            return retVal.Body.AddBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessResponse> UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.AddBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequest request) {
            return base.Channel.AddBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessResponse> AddBussinessAsync(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.AddBussinessRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            inValue.Body.bussinessOwnerId = bussinessOwnerId;
            return ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).AddBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessResponse UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.DeleteBussiness(UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequest request) {
            return base.Channel.DeleteBussiness(request);
        }
        
        public bool DeleteBussiness(string bussinessId) {
            UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessResponse retVal = ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).DeleteBussiness(inValue);
            return retVal.Body.DeleteBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessResponse> UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.DeleteBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequest request) {
            return base.Channel.DeleteBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessResponse> DeleteBussinessAsync(string bussinessId) {
            UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.DeleteBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            return ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).DeleteBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessResponse UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.ApproveBussiness(UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequest request) {
            return base.Channel.ApproveBussiness(request);
        }
        
        public bool ApproveBussiness(string bussinessId) {
            UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessResponse retVal = ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).ApproveBussiness(inValue);
            return retVal.Body.ApproveBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessResponse> UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.ApproveBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequest request) {
            return base.Channel.ApproveBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessResponse> ApproveBussinessAsync(string bussinessId) {
            UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.ApproveBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            return ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).ApproveBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessResponse UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.UpdateBussiness(UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequest request) {
            return base.Channel.UpdateBussiness(request);
        }
        
        public bool UpdateBussiness(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessResponse retVal = ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).UpdateBussiness(inValue);
            return retVal.Body.UpdateBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessResponse> UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.UpdateBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequest request) {
            return base.Channel.UpdateBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessResponse> UpdateBussinessAsync(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.UpdateBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            return ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).UpdateBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameResponse UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.FindBussinessByName(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequest request) {
            return base.Channel.FindBussinessByName(request);
        }
        
        public string FindBussinessByName(string bussinessName) {
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequestBody();
            inValue.Body.bussinessName = bussinessName;
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameResponse retVal = ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).FindBussinessByName(inValue);
            return retVal.Body.FindBussinessByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameResponse> UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.FindBussinessByNameAsync(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequest request) {
            return base.Channel.FindBussinessByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameResponse> FindBussinessByNameAsync(string bussinessName) {
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByNameRequestBody();
            inValue.Body.bussinessName = bussinessName;
            return ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).FindBussinessByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerResponse UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.FindBussinessOfOwner(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequest request) {
            return base.Channel.FindBussinessOfOwner(request);
        }
        
        public string FindBussinessOfOwner(string ownerID) {
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequestBody();
            inValue.Body.ownerID = ownerID;
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerResponse retVal = ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).FindBussinessOfOwner(inValue);
            return retVal.Body.FindBussinessOfOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerResponse> UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.FindBussinessOfOwnerAsync(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequest request) {
            return base.Channel.FindBussinessOfOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerResponse> FindBussinessOfOwnerAsync(string ownerID) {
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessOfOwnerRequestBody();
            inValue.Body.ownerID = ownerID;
            return ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).FindBussinessOfOwnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryResponse UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.FindBussinessByCategory(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequest request) {
            return base.Channel.FindBussinessByCategory(request);
        }
        
        public string FindBussinessByCategory(string category) {
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequestBody();
            inValue.Body.category = category;
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryResponse retVal = ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).FindBussinessByCategory(inValue);
            return retVal.Body.FindBussinessByCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryResponse> UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.FindBussinessByCategoryAsync(UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequest request) {
            return base.Channel.FindBussinessByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryResponse> FindBussinessByCategoryAsync(string category) {
            UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.FindBussinessByCategoryRequestBody();
            inValue.Body.category = category;
            return ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).FindBussinessByCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessResponse UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.GetAllUnapprovedBussiness(UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequest request) {
            return base.Channel.GetAllUnapprovedBussiness(request);
        }
        
        public string GetAllUnapprovedBussiness() {
            UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequestBody();
            UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessResponse retVal = ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).GetAllUnapprovedBussiness(inValue);
            return retVal.Body.GetAllUnapprovedBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessResponse> UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap.GetAllUnapprovedBussinessAsync(UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequest request) {
            return base.Channel.GetAllUnapprovedBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessResponse> GetAllUnapprovedBussinessAsync() {
            UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponServiceReference.GetAllUnapprovedBussinessRequestBody();
            return ((UnitTestWebCuponSystemService.CuponServiceReference.BussinessServicesSoap)(this)).GetAllUnapprovedBussinessAsync(inValue);
        }
    }
}
