//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWebCuponSystemService.UserService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="UserService.UserServicesSoap")]
    public interface UserServicesSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.AuthenticateUserResponse AuthenticateUser(UnitTestWebCuponSystemService.UserService.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.AuthenticateUserResponse> AuthenticateUserAsync(UnitTestWebCuponSystemService.UserService.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BussinessOwnerRegister", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterResponse BussinessOwnerRegister(UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BussinessOwnerRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterResponse> BussinessOwnerRegisterAsync(UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBasicUser", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.UpdateBasicUserResponse UpdateBasicUser(UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBasicUser", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.UpdateBasicUserResponse> UpdateBasicUserAsync(UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBasicUserByName_Email", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailResponse FindBasicUserByName_Email(UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBasicUserByName_Email", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailResponse> FindBasicUserByName_EmailAsync(UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBasicUserByID", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.FindBasicUserByIDResponse FindBasicUserByID(UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBasicUserByID", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBasicUserByIDResponse> FindBasicUserByIDAsync(UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequest request);
        
        // CODEGEN: Generating message contract since element name id from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessOwnerByID", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDResponse FindBussinessOwnerByID(UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessOwnerByID", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDResponse> FindBussinessOwnerByIDAsync(UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.ChangePasswordResponse ChangePassword(UnitTestWebCuponSystemService.UserService.ChangePasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.ChangePasswordResponse> ChangePasswordAsync(UnitTestWebCuponSystemService.UserService.ChangePasswordRequest request);
        
        // CODEGEN: Generating message contract since element name userId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateNewPassword", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.GenerateNewPasswordResponse GenerateNewPassword(UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateNewPassword", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.GenerateNewPasswordResponse> GenerateNewPasswordAsync(UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPreference", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.AddPreferenceResponse AddPreference(UnitTestWebCuponSystemService.UserService.AddPreferenceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddPreference", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.AddPreferenceResponse> AddPreferenceAsync(UnitTestWebCuponSystemService.UserService.AddPreferenceRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BasicUserRegister", ReplyAction="*")]
        UnitTestWebCuponSystemService.UserService.BasicUserRegisterResponse BasicUserRegister(UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BasicUserRegister", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.BasicUserRegisterResponse> BasicUserRegisterAsync(UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(UnitTestWebCuponSystemService.UserService.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(UnitTestWebCuponSystemService.UserService.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(string AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BussinessOwnerRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BussinessOwnerRegister", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequestBody Body;
        
        public BussinessOwnerRegisterRequest() {
        }
        
        public BussinessOwnerRegisterRequest(UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BussinessOwnerRegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string photo;
        
        public BussinessOwnerRegisterRequestBody() {
        }
        
        public BussinessOwnerRegisterRequestBody(string userName, string password, string email, string photo) {
            this.userName = userName;
            this.password = password;
            this.email = email;
            this.photo = photo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BussinessOwnerRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BussinessOwnerRegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterResponseBody Body;
        
        public BussinessOwnerRegisterResponse() {
        }
        
        public BussinessOwnerRegisterResponse(UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BussinessOwnerRegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BussinessOwnerRegisterResult;
        
        public BussinessOwnerRegisterResponseBody() {
        }
        
        public BussinessOwnerRegisterResponseBody(string BussinessOwnerRegisterResult) {
            this.BussinessOwnerRegisterResult = BussinessOwnerRegisterResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBasicUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBasicUser", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequestBody Body;
        
        public UpdateBasicUserRequest() {
        }
        
        public UpdateBasicUserRequest(UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBasicUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string longtitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string photo;
        
        public UpdateBasicUserRequestBody() {
        }
        
        public UpdateBasicUserRequestBody(string userId, string userName, string password, string email, string phoneNumber, string latitude, string longtitude, string photo) {
            this.userId = userId;
            this.userName = userName;
            this.password = password;
            this.email = email;
            this.phoneNumber = phoneNumber;
            this.latitude = latitude;
            this.longtitude = longtitude;
            this.photo = photo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBasicUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBasicUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.UpdateBasicUserResponseBody Body;
        
        public UpdateBasicUserResponse() {
        }
        
        public UpdateBasicUserResponse(UnitTestWebCuponSystemService.UserService.UpdateBasicUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBasicUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateBasicUserResult;
        
        public UpdateBasicUserResponseBody() {
        }
        
        public UpdateBasicUserResponseBody(bool UpdateBasicUserResult) {
            this.UpdateBasicUserResult = UpdateBasicUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBasicUserByName_EmailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBasicUserByName_Email", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequestBody Body;
        
        public FindBasicUserByName_EmailRequest() {
        }
        
        public FindBasicUserByName_EmailRequest(UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBasicUserByName_EmailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string email;
        
        public FindBasicUserByName_EmailRequestBody() {
        }
        
        public FindBasicUserByName_EmailRequestBody(string userName, string email) {
            this.userName = userName;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBasicUserByName_EmailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBasicUserByName_EmailResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailResponseBody Body;
        
        public FindBasicUserByName_EmailResponse() {
        }
        
        public FindBasicUserByName_EmailResponse(UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBasicUserByName_EmailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBasicUserByName_EmailResult;
        
        public FindBasicUserByName_EmailResponseBody() {
        }
        
        public FindBasicUserByName_EmailResponseBody(string FindBasicUserByName_EmailResult) {
            this.FindBasicUserByName_EmailResult = FindBasicUserByName_EmailResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBasicUserByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBasicUserByID", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequestBody Body;
        
        public FindBasicUserByIDRequest() {
        }
        
        public FindBasicUserByIDRequest(UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBasicUserByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public FindBasicUserByIDRequestBody() {
        }
        
        public FindBasicUserByIDRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBasicUserByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBasicUserByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.FindBasicUserByIDResponseBody Body;
        
        public FindBasicUserByIDResponse() {
        }
        
        public FindBasicUserByIDResponse(UnitTestWebCuponSystemService.UserService.FindBasicUserByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBasicUserByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBasicUserByIDResult;
        
        public FindBasicUserByIDResponseBody() {
        }
        
        public FindBasicUserByIDResponseBody(string FindBasicUserByIDResult) {
            this.FindBasicUserByIDResult = FindBasicUserByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessOwnerByIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessOwnerByID", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequestBody Body;
        
        public FindBussinessOwnerByIDRequest() {
        }
        
        public FindBussinessOwnerByIDRequest(UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessOwnerByIDRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public FindBussinessOwnerByIDRequestBody() {
        }
        
        public FindBussinessOwnerByIDRequestBody(string id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessOwnerByIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessOwnerByIDResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDResponseBody Body;
        
        public FindBussinessOwnerByIDResponse() {
        }
        
        public FindBussinessOwnerByIDResponse(UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessOwnerByIDResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessOwnerByIDResult;
        
        public FindBussinessOwnerByIDResponseBody() {
        }
        
        public FindBussinessOwnerByIDResponseBody(string FindBussinessOwnerByIDResult) {
            this.FindBussinessOwnerByIDResult = FindBussinessOwnerByIDResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePassword", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.ChangePasswordRequestBody Body;
        
        public ChangePasswordRequest() {
        }
        
        public ChangePasswordRequest(UnitTestWebCuponSystemService.UserService.ChangePasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newPassword;
        
        public ChangePasswordRequestBody() {
        }
        
        public ChangePasswordRequestBody(string userId, string newPassword) {
            this.userId = userId;
            this.newPassword = newPassword;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangePasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangePasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.ChangePasswordResponseBody Body;
        
        public ChangePasswordResponse() {
        }
        
        public ChangePasswordResponse(UnitTestWebCuponSystemService.UserService.ChangePasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangePasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ChangePasswordResult;
        
        public ChangePasswordResponseBody() {
        }
        
        public ChangePasswordResponseBody(bool ChangePasswordResult) {
            this.ChangePasswordResult = ChangePasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateNewPasswordRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateNewPassword", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequestBody Body;
        
        public GenerateNewPasswordRequest() {
        }
        
        public GenerateNewPasswordRequest(UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateNewPasswordRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public GenerateNewPasswordRequestBody() {
        }
        
        public GenerateNewPasswordRequestBody(string userId) {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateNewPasswordResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateNewPasswordResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.GenerateNewPasswordResponseBody Body;
        
        public GenerateNewPasswordResponse() {
        }
        
        public GenerateNewPasswordResponse(UnitTestWebCuponSystemService.UserService.GenerateNewPasswordResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateNewPasswordResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateNewPasswordResult;
        
        public GenerateNewPasswordResponseBody() {
        }
        
        public GenerateNewPasswordResponseBody(string GenerateNewPasswordResult) {
            this.GenerateNewPasswordResult = GenerateNewPasswordResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPreferenceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPreference", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.AddPreferenceRequestBody Body;
        
        public AddPreferenceRequest() {
        }
        
        public AddPreferenceRequest(UnitTestWebCuponSystemService.UserService.AddPreferenceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPreferenceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userId;
        
        public AddPreferenceRequestBody() {
        }
        
        public AddPreferenceRequestBody(string category, string userId) {
            this.category = category;
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddPreferenceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddPreferenceResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.AddPreferenceResponseBody Body;
        
        public AddPreferenceResponse() {
        }
        
        public AddPreferenceResponse(UnitTestWebCuponSystemService.UserService.AddPreferenceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddPreferenceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddPreferenceResult;
        
        public AddPreferenceResponseBody() {
        }
        
        public AddPreferenceResponseBody(bool AddPreferenceResult) {
            this.AddPreferenceResult = AddPreferenceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BasicUserRegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BasicUserRegister", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequestBody Body;
        
        public BasicUserRegisterRequest() {
        }
        
        public BasicUserRegisterRequest(UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BasicUserRegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string birthDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string longitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string photo;
        
        public BasicUserRegisterRequestBody() {
        }
        
        public BasicUserRegisterRequestBody(string userName, string password, string email, string gender, string phoneNumber, string birthDate, string longitude, string latitude, string photo) {
            this.userName = userName;
            this.password = password;
            this.email = email;
            this.gender = gender;
            this.phoneNumber = phoneNumber;
            this.birthDate = birthDate;
            this.longitude = longitude;
            this.latitude = latitude;
            this.photo = photo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BasicUserRegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="BasicUserRegisterResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.UserService.BasicUserRegisterResponseBody Body;
        
        public BasicUserRegisterResponse() {
        }
        
        public BasicUserRegisterResponse(UnitTestWebCuponSystemService.UserService.BasicUserRegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class BasicUserRegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string BasicUserRegisterResult;
        
        public BasicUserRegisterResponseBody() {
        }
        
        public BasicUserRegisterResponseBody(string BasicUserRegisterResult) {
            this.BasicUserRegisterResult = BasicUserRegisterResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UserServicesSoapChannel : UnitTestWebCuponSystemService.UserService.UserServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UserServicesSoapClient : System.ServiceModel.ClientBase<UnitTestWebCuponSystemService.UserService.UserServicesSoap>, UnitTestWebCuponSystemService.UserService.UserServicesSoap {
        
        public UserServicesSoapClient() {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UserServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.AuthenticateUserResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.AuthenticateUser(UnitTestWebCuponSystemService.UserService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public string AuthenticateUser(string userName, string password) {
            UnitTestWebCuponSystemService.UserService.AuthenticateUserRequest inValue = new UnitTestWebCuponSystemService.UserService.AuthenticateUserRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.AuthenticateUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            UnitTestWebCuponSystemService.UserService.AuthenticateUserResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.AuthenticateUserResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.AuthenticateUserAsync(UnitTestWebCuponSystemService.UserService.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.AuthenticateUserResponse> AuthenticateUserAsync(string userName, string password) {
            UnitTestWebCuponSystemService.UserService.AuthenticateUserRequest inValue = new UnitTestWebCuponSystemService.UserService.AuthenticateUserRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.AuthenticateUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.BussinessOwnerRegister(UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequest request) {
            return base.Channel.BussinessOwnerRegister(request);
        }
        
        public string BussinessOwnerRegister(string userName, string password, string email, string photo) {
            UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequest inValue = new UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.photo = photo;
            UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).BussinessOwnerRegister(inValue);
            return retVal.Body.BussinessOwnerRegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.BussinessOwnerRegisterAsync(UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequest request) {
            return base.Channel.BussinessOwnerRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterResponse> BussinessOwnerRegisterAsync(string userName, string password, string email, string photo) {
            UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequest inValue = new UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.BussinessOwnerRegisterRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.photo = photo;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).BussinessOwnerRegisterAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.UpdateBasicUserResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.UpdateBasicUser(UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequest request) {
            return base.Channel.UpdateBasicUser(request);
        }
        
        public bool UpdateBasicUser(string userId, string userName, string password, string email, string phoneNumber, string latitude, string longtitude, string photo) {
            UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequest inValue = new UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            UnitTestWebCuponSystemService.UserService.UpdateBasicUserResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).UpdateBasicUser(inValue);
            return retVal.Body.UpdateBasicUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.UpdateBasicUserResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.UpdateBasicUserAsync(UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequest request) {
            return base.Channel.UpdateBasicUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.UpdateBasicUserResponse> UpdateBasicUserAsync(string userId, string userName, string password, string email, string phoneNumber, string latitude, string longtitude, string photo) {
            UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequest inValue = new UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.UpdateBasicUserRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).UpdateBasicUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.FindBasicUserByName_Email(UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequest request) {
            return base.Channel.FindBasicUserByName_Email(request);
        }
        
        public string FindBasicUserByName_Email(string userName, string email) {
            UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequest inValue = new UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.email = email;
            UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).FindBasicUserByName_Email(inValue);
            return retVal.Body.FindBasicUserByName_EmailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.FindBasicUserByName_EmailAsync(UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequest request) {
            return base.Channel.FindBasicUserByName_EmailAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailResponse> FindBasicUserByName_EmailAsync(string userName, string email) {
            UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequest inValue = new UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.FindBasicUserByName_EmailRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.email = email;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).FindBasicUserByName_EmailAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.FindBasicUserByIDResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.FindBasicUserByID(UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequest request) {
            return base.Channel.FindBasicUserByID(request);
        }
        
        public string FindBasicUserByID(string id) {
            UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequest inValue = new UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequestBody();
            inValue.Body.id = id;
            UnitTestWebCuponSystemService.UserService.FindBasicUserByIDResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).FindBasicUserByID(inValue);
            return retVal.Body.FindBasicUserByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBasicUserByIDResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.FindBasicUserByIDAsync(UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequest request) {
            return base.Channel.FindBasicUserByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBasicUserByIDResponse> FindBasicUserByIDAsync(string id) {
            UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequest inValue = new UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.FindBasicUserByIDRequestBody();
            inValue.Body.id = id;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).FindBasicUserByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.FindBussinessOwnerByID(UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequest request) {
            return base.Channel.FindBussinessOwnerByID(request);
        }
        
        public string FindBussinessOwnerByID(string id) {
            UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequest inValue = new UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequestBody();
            inValue.Body.id = id;
            UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).FindBussinessOwnerByID(inValue);
            return retVal.Body.FindBussinessOwnerByIDResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.FindBussinessOwnerByIDAsync(UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequest request) {
            return base.Channel.FindBussinessOwnerByIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDResponse> FindBussinessOwnerByIDAsync(string id) {
            UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequest inValue = new UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.FindBussinessOwnerByIDRequestBody();
            inValue.Body.id = id;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).FindBussinessOwnerByIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.ChangePasswordResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.ChangePassword(UnitTestWebCuponSystemService.UserService.ChangePasswordRequest request) {
            return base.Channel.ChangePassword(request);
        }
        
        public bool ChangePassword(string userId, string newPassword) {
            UnitTestWebCuponSystemService.UserService.ChangePasswordRequest inValue = new UnitTestWebCuponSystemService.UserService.ChangePasswordRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.ChangePasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.newPassword = newPassword;
            UnitTestWebCuponSystemService.UserService.ChangePasswordResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).ChangePassword(inValue);
            return retVal.Body.ChangePasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.ChangePasswordResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.ChangePasswordAsync(UnitTestWebCuponSystemService.UserService.ChangePasswordRequest request) {
            return base.Channel.ChangePasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.ChangePasswordResponse> ChangePasswordAsync(string userId, string newPassword) {
            UnitTestWebCuponSystemService.UserService.ChangePasswordRequest inValue = new UnitTestWebCuponSystemService.UserService.ChangePasswordRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.ChangePasswordRequestBody();
            inValue.Body.userId = userId;
            inValue.Body.newPassword = newPassword;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).ChangePasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.GenerateNewPasswordResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.GenerateNewPassword(UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequest request) {
            return base.Channel.GenerateNewPassword(request);
        }
        
        public string GenerateNewPassword(string userId) {
            UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequest inValue = new UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequestBody();
            inValue.Body.userId = userId;
            UnitTestWebCuponSystemService.UserService.GenerateNewPasswordResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).GenerateNewPassword(inValue);
            return retVal.Body.GenerateNewPasswordResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.GenerateNewPasswordResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.GenerateNewPasswordAsync(UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequest request) {
            return base.Channel.GenerateNewPasswordAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.GenerateNewPasswordResponse> GenerateNewPasswordAsync(string userId) {
            UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequest inValue = new UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.GenerateNewPasswordRequestBody();
            inValue.Body.userId = userId;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).GenerateNewPasswordAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.AddPreferenceResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.AddPreference(UnitTestWebCuponSystemService.UserService.AddPreferenceRequest request) {
            return base.Channel.AddPreference(request);
        }
        
        public bool AddPreference(string category, string userId) {
            UnitTestWebCuponSystemService.UserService.AddPreferenceRequest inValue = new UnitTestWebCuponSystemService.UserService.AddPreferenceRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.AddPreferenceRequestBody();
            inValue.Body.category = category;
            inValue.Body.userId = userId;
            UnitTestWebCuponSystemService.UserService.AddPreferenceResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).AddPreference(inValue);
            return retVal.Body.AddPreferenceResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.AddPreferenceResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.AddPreferenceAsync(UnitTestWebCuponSystemService.UserService.AddPreferenceRequest request) {
            return base.Channel.AddPreferenceAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.AddPreferenceResponse> AddPreferenceAsync(string category, string userId) {
            UnitTestWebCuponSystemService.UserService.AddPreferenceRequest inValue = new UnitTestWebCuponSystemService.UserService.AddPreferenceRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.AddPreferenceRequestBody();
            inValue.Body.category = category;
            inValue.Body.userId = userId;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).AddPreferenceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.UserService.BasicUserRegisterResponse UnitTestWebCuponSystemService.UserService.UserServicesSoap.BasicUserRegister(UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequest request) {
            return base.Channel.BasicUserRegister(request);
        }
        
        public string BasicUserRegister(string userName, string password, string email, string gender, string phoneNumber, string birthDate, string longitude, string latitude, string photo) {
            UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequest inValue = new UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.gender = gender;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.birthDate = birthDate;
            inValue.Body.longitude = longitude;
            inValue.Body.latitude = latitude;
            inValue.Body.photo = photo;
            UnitTestWebCuponSystemService.UserService.BasicUserRegisterResponse retVal = ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).BasicUserRegister(inValue);
            return retVal.Body.BasicUserRegisterResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.BasicUserRegisterResponse> UnitTestWebCuponSystemService.UserService.UserServicesSoap.BasicUserRegisterAsync(UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequest request) {
            return base.Channel.BasicUserRegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.UserService.BasicUserRegisterResponse> BasicUserRegisterAsync(string userName, string password, string email, string gender, string phoneNumber, string birthDate, string longitude, string latitude, string photo) {
            UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequest inValue = new UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequest();
            inValue.Body = new UnitTestWebCuponSystemService.UserService.BasicUserRegisterRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.gender = gender;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.birthDate = birthDate;
            inValue.Body.longitude = longitude;
            inValue.Body.latitude = latitude;
            inValue.Body.photo = photo;
            return ((UnitTestWebCuponSystemService.UserService.UserServicesSoap)(this)).BasicUserRegisterAsync(inValue);
        }
    }
}
