//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuponWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bussiness
    {
        public Bussiness()
        {
            this.BussinessCupons = new HashSet<BussinessCupon>();
            this.Location = new Location();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Category Category { get; set; }
        public string Photo { get; set; }
    
        public Location Location { get; set; }
    
        public virtual BussinessOwner BussinessOwner { get; set; }
        public virtual ICollection<BussinessCupon> BussinessCupons { get; set; }
    }
}
