//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuponWebSite
{
    using System;
    
    public enum Category : int
    {
        Resturants = 0,
        Shopping = 1,
        HealthCare = 2,
        OfficeAndElectronics = 3,
        Vacations = 4,
        Pleasure = 5
    }
}
