//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuponWebSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ModelContainer : DbContext
    {
        public ModelContainer()
            : base("name=ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Cupon> Cupons { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<Bussiness> Bussinesses { get; set; }
        public DbSet<Preference> Preferences { get; set; }
        public DbSet<PurchasedCupon> PurchasedCupons { get; set; }
        public DbSet<Log> Logs { get; set; }
    }
}
