//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuponWebSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchasedCupon
    {
        public int Id { get; set; }
        public string SerialKey { get; set; }
        public CuponState State { get; set; }
        public Rate Rate { get; set; }
    
        public virtual BasicUser BasicUser { get; set; }
        public virtual BussinessCupon BussinessCupon { get; set; }
    }
}
