//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuponWebSite
{
    using System;
    
    public enum Rate : int
    {
        One = 0,
        Two = 1,
        Three = 2,
        Four = 3,
        Five = 4,
        NA = 5
    }
}
