//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CuponWebSite
{
    using System;
    
    public enum RecommendationType : int
    {
        Off = 0,
        Location = 1,
        Preference = 2,
        Combined = 3
    }
}
