//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWebCuponSystemService.BussinessService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BussinessService.BussinessServicesSoap")]
    public interface BussinessServicesSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessService.AddBussinessResponse AddBussiness(UnitTestWebCuponSystemService.BussinessService.AddBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.AddBussinessResponse> AddBussinessAsync(UnitTestWebCuponSystemService.BussinessService.AddBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessService.DeleteBussinessResponse DeleteBussiness(UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.DeleteBussinessResponse> DeleteBussinessAsync(UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessService.UpdateBussinessResponse UpdateBussiness(UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.UpdateBussinessResponse> UpdateBussinessAsync(UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByName", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameResponse FindBussinessByName(UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByName", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameResponse> FindBussinessByNameAsync(UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequest request);
        
        // CODEGEN: Generating message contract since element name ownerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessOfOwner", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerResponse FindBussinessOfOwner(UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessOfOwner", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerResponse> FindBussinessOfOwnerAsync(UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByCategory", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryResponse FindBussinessByCategory(UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryResponse> FindBussinessByCategoryAsync(UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.AddBussinessRequestBody Body;
        
        public AddBussinessRequest() {
        }
        
        public AddBussinessRequest(UnitTestWebCuponSystemService.BussinessService.AddBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string longtitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string photo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string bussinessOwnerId;
        
        public AddBussinessRequestBody() {
        }
        
        public AddBussinessRequestBody(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            this.name = name;
            this.description = description;
            this.category = category;
            this.latitude = latitude;
            this.longtitude = longtitude;
            this.photo = photo;
            this.bussinessOwnerId = bussinessOwnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.AddBussinessResponseBody Body;
        
        public AddBussinessResponse() {
        }
        
        public AddBussinessResponse(UnitTestWebCuponSystemService.BussinessService.AddBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddBussinessResult;
        
        public AddBussinessResponseBody() {
        }
        
        public AddBussinessResponseBody(bool AddBussinessResult) {
            this.AddBussinessResult = AddBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequestBody Body;
        
        public DeleteBussinessRequest() {
        }
        
        public DeleteBussinessRequest(UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessId;
        
        public DeleteBussinessRequestBody() {
        }
        
        public DeleteBussinessRequestBody(string bussinessId) {
            this.bussinessId = bussinessId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.DeleteBussinessResponseBody Body;
        
        public DeleteBussinessResponse() {
        }
        
        public DeleteBussinessResponse(UnitTestWebCuponSystemService.BussinessService.DeleteBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteBussinessResult;
        
        public DeleteBussinessResponseBody() {
        }
        
        public DeleteBussinessResponseBody(bool DeleteBussinessResult) {
            this.DeleteBussinessResult = DeleteBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequestBody Body;
        
        public UpdateBussinessRequest() {
        }
        
        public UpdateBussinessRequest(UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string longtitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string photo;
        
        public UpdateBussinessRequestBody() {
        }
        
        public UpdateBussinessRequestBody(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            this.bussinessId = bussinessId;
            this.name = name;
            this.description = description;
            this.category = category;
            this.latitude = latitude;
            this.longtitude = longtitude;
            this.photo = photo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.UpdateBussinessResponseBody Body;
        
        public UpdateBussinessResponse() {
        }
        
        public UpdateBussinessResponse(UnitTestWebCuponSystemService.BussinessService.UpdateBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateBussinessResult;
        
        public UpdateBussinessResponseBody() {
        }
        
        public UpdateBussinessResponseBody(bool UpdateBussinessResult) {
            this.UpdateBussinessResult = UpdateBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByName", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequestBody Body;
        
        public FindBussinessByNameRequest() {
        }
        
        public FindBussinessByNameRequest(UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessName;
        
        public FindBussinessByNameRequestBody() {
        }
        
        public FindBussinessByNameRequestBody(string bussinessName) {
            this.bussinessName = bussinessName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameResponseBody Body;
        
        public FindBussinessByNameResponse() {
        }
        
        public FindBussinessByNameResponse(UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessByNameResult;
        
        public FindBussinessByNameResponseBody() {
        }
        
        public FindBussinessByNameResponseBody(string FindBussinessByNameResult) {
            this.FindBussinessByNameResult = FindBussinessByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessOfOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessOfOwner", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequestBody Body;
        
        public FindBussinessOfOwnerRequest() {
        }
        
        public FindBussinessOfOwnerRequest(UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessOfOwnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ownerID;
        
        public FindBussinessOfOwnerRequestBody() {
        }
        
        public FindBussinessOfOwnerRequestBody(string ownerID) {
            this.ownerID = ownerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessOfOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessOfOwnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerResponseBody Body;
        
        public FindBussinessOfOwnerResponse() {
        }
        
        public FindBussinessOfOwnerResponse(UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessOfOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessOfOwnerResult;
        
        public FindBussinessOfOwnerResponseBody() {
        }
        
        public FindBussinessOfOwnerResponseBody(string FindBussinessOfOwnerResult) {
            this.FindBussinessOfOwnerResult = FindBussinessOfOwnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByCategory", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequestBody Body;
        
        public FindBussinessByCategoryRequest() {
        }
        
        public FindBussinessByCategoryRequest(UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public FindBussinessByCategoryRequestBody() {
        }
        
        public FindBussinessByCategoryRequestBody(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryResponseBody Body;
        
        public FindBussinessByCategoryResponse() {
        }
        
        public FindBussinessByCategoryResponse(UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessByCategoryResult;
        
        public FindBussinessByCategoryResponseBody() {
        }
        
        public FindBussinessByCategoryResponseBody(string FindBussinessByCategoryResult) {
            this.FindBussinessByCategoryResult = FindBussinessByCategoryResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BussinessServicesSoapChannel : UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BussinessServicesSoapClient : System.ServiceModel.ClientBase<UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap>, UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap {
        
        public BussinessServicesSoapClient() {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BussinessServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessService.AddBussinessResponse UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.AddBussiness(UnitTestWebCuponSystemService.BussinessService.AddBussinessRequest request) {
            return base.Channel.AddBussiness(request);
        }
        
        public bool AddBussiness(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            UnitTestWebCuponSystemService.BussinessService.AddBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessService.AddBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.AddBussinessRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            inValue.Body.bussinessOwnerId = bussinessOwnerId;
            UnitTestWebCuponSystemService.BussinessService.AddBussinessResponse retVal = ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).AddBussiness(inValue);
            return retVal.Body.AddBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.AddBussinessResponse> UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.AddBussinessAsync(UnitTestWebCuponSystemService.BussinessService.AddBussinessRequest request) {
            return base.Channel.AddBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.AddBussinessResponse> AddBussinessAsync(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            UnitTestWebCuponSystemService.BussinessService.AddBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessService.AddBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.AddBussinessRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            inValue.Body.bussinessOwnerId = bussinessOwnerId;
            return ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).AddBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessService.DeleteBussinessResponse UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.DeleteBussiness(UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequest request) {
            return base.Channel.DeleteBussiness(request);
        }
        
        public bool DeleteBussiness(string bussinessId) {
            UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            UnitTestWebCuponSystemService.BussinessService.DeleteBussinessResponse retVal = ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).DeleteBussiness(inValue);
            return retVal.Body.DeleteBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.DeleteBussinessResponse> UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.DeleteBussinessAsync(UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequest request) {
            return base.Channel.DeleteBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.DeleteBussinessResponse> DeleteBussinessAsync(string bussinessId) {
            UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.DeleteBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            return ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).DeleteBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessService.UpdateBussinessResponse UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.UpdateBussiness(UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequest request) {
            return base.Channel.UpdateBussiness(request);
        }
        
        public bool UpdateBussiness(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            UnitTestWebCuponSystemService.BussinessService.UpdateBussinessResponse retVal = ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).UpdateBussiness(inValue);
            return retVal.Body.UpdateBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.UpdateBussinessResponse> UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.UpdateBussinessAsync(UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequest request) {
            return base.Channel.UpdateBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.UpdateBussinessResponse> UpdateBussinessAsync(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.UpdateBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            return ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).UpdateBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameResponse UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.FindBussinessByName(UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequest request) {
            return base.Channel.FindBussinessByName(request);
        }
        
        public string FindBussinessByName(string bussinessName) {
            UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequest inValue = new UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequestBody();
            inValue.Body.bussinessName = bussinessName;
            UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameResponse retVal = ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).FindBussinessByName(inValue);
            return retVal.Body.FindBussinessByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameResponse> UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.FindBussinessByNameAsync(UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequest request) {
            return base.Channel.FindBussinessByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameResponse> FindBussinessByNameAsync(string bussinessName) {
            UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequest inValue = new UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.FindBussinessByNameRequestBody();
            inValue.Body.bussinessName = bussinessName;
            return ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).FindBussinessByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerResponse UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.FindBussinessOfOwner(UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequest request) {
            return base.Channel.FindBussinessOfOwner(request);
        }
        
        public string FindBussinessOfOwner(string ownerID) {
            UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequest inValue = new UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequestBody();
            inValue.Body.ownerID = ownerID;
            UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerResponse retVal = ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).FindBussinessOfOwner(inValue);
            return retVal.Body.FindBussinessOfOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerResponse> UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.FindBussinessOfOwnerAsync(UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequest request) {
            return base.Channel.FindBussinessOfOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerResponse> FindBussinessOfOwnerAsync(string ownerID) {
            UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequest inValue = new UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.FindBussinessOfOwnerRequestBody();
            inValue.Body.ownerID = ownerID;
            return ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).FindBussinessOfOwnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryResponse UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.FindBussinessByCategory(UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequest request) {
            return base.Channel.FindBussinessByCategory(request);
        }
        
        public string FindBussinessByCategory(string category) {
            UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequest inValue = new UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequestBody();
            inValue.Body.category = category;
            UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryResponse retVal = ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).FindBussinessByCategory(inValue);
            return retVal.Body.FindBussinessByCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryResponse> UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap.FindBussinessByCategoryAsync(UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequest request) {
            return base.Channel.FindBussinessByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryResponse> FindBussinessByCategoryAsync(string category) {
            UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequest inValue = new UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessService.FindBussinessByCategoryRequestBody();
            inValue.Body.category = category;
            return ((UnitTestWebCuponSystemService.BussinessService.BussinessServicesSoap)(this)).FindBussinessByCategoryAsync(inValue);
        }
    }
}
