//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWebCuponSystemService.CuponSystemWebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gender", Namespace="http://tempuri.org/")]
    public enum Gender : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Male = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Female = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private double LongtitudeField;
        
        private double LatitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Category", Namespace="http://tempuri.org/")]
    public enum Category : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Resturants = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Shopping = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        HealthCare = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OfficeAndElectronics = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Vacations = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Pleasure = 5,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CuponSystemWebServiceReference.CuponSystemWebServiceSoap")]
    public interface CuponSystemWebServiceSoap {
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserResponse AuthenticateUser(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AuthenticateUser", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserResponse> AuthenticateUserAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussinessOwner", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerResponse AddBussinessOwner(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussinessOwner", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerResponse> AddBussinessOwnerAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBasicUser", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserResponse AddBasicUser(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBasicUser", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserResponse> AddBasicUserAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequest request);
        
        // CODEGEN: Generating message contract since element name userName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSystemAdmin", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminResponse AddSystemAdmin(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddSystemAdmin", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminResponse> AddSystemAdminAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessResponse AddBussiness(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessResponse> AddBussinessAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUser", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequestBody Body;
        
        public AuthenticateUserRequest() {
        }
        
        public AuthenticateUserRequest(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public AuthenticateUserRequestBody() {
        }
        
        public AuthenticateUserRequestBody(string userName, string password) {
            this.userName = userName;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthenticateUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthenticateUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserResponseBody Body;
        
        public AuthenticateUserResponse() {
        }
        
        public AuthenticateUserResponse(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AuthenticateUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AuthenticateUserResult;
        
        public AuthenticateUserResponseBody() {
        }
        
        public AuthenticateUserResponseBody(bool AuthenticateUserResult) {
            this.AuthenticateUserResult = AuthenticateUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussinessOwner", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequestBody Body;
        
        public AddBussinessOwnerRequest() {
        }
        
        public AddBussinessOwnerRequest(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessOwnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        public AddBussinessOwnerRequestBody() {
        }
        
        public AddBussinessOwnerRequestBody(string userName, string password, string email) {
            this.userName = userName;
            this.password = password;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussinessOwnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerResponseBody Body;
        
        public AddBussinessOwnerResponse() {
        }
        
        public AddBussinessOwnerResponse(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddBussinessOwnerResult;
        
        public AddBussinessOwnerResponseBody() {
        }
        
        public AddBussinessOwnerResponseBody(bool AddBussinessOwnerResult) {
            this.AddBussinessOwnerResult = AddBussinessOwnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBasicUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBasicUser", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequestBody Body;
        
        public AddBasicUserRequest() {
        }
        
        public AddBasicUserRequest(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBasicUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Gender gender;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string phoneNumber;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime birthDate;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Location location;
        
        public AddBasicUserRequestBody() {
        }
        
        public AddBasicUserRequestBody(string userName, string password, string email, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Gender gender, string phoneNumber, System.DateTime birthDate, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Location location) {
            this.userName = userName;
            this.password = password;
            this.email = email;
            this.gender = gender;
            this.phoneNumber = phoneNumber;
            this.birthDate = birthDate;
            this.location = location;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBasicUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBasicUserResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserResponseBody Body;
        
        public AddBasicUserResponse() {
        }
        
        public AddBasicUserResponse(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBasicUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddBasicUserResult;
        
        public AddBasicUserResponseBody() {
        }
        
        public AddBasicUserResponseBody(bool AddBasicUserResult) {
            this.AddBasicUserResult = AddBasicUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSystemAdminRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSystemAdmin", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequestBody Body;
        
        public AddSystemAdminRequest() {
        }
        
        public AddSystemAdminRequest(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSystemAdminRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string email;
        
        public AddSystemAdminRequestBody() {
        }
        
        public AddSystemAdminRequestBody(string userName, string password, string email) {
            this.userName = userName;
            this.password = password;
            this.email = email;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddSystemAdminResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddSystemAdminResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminResponseBody Body;
        
        public AddSystemAdminResponse() {
        }
        
        public AddSystemAdminResponse(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddSystemAdminResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddSystemAdminResult;
        
        public AddSystemAdminResponseBody() {
        }
        
        public AddSystemAdminResponseBody(bool AddSystemAdminResult) {
            this.AddSystemAdminResult = AddSystemAdminResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequestBody Body;
        
        public AddBussinessRequest() {
        }
        
        public AddBussinessRequest(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Category category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Location location;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public int bussinessOwnerId;
        
        public AddBussinessRequestBody() {
        }
        
        public AddBussinessRequestBody(string name, string description, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Category category, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Location location, int bussinessOwnerId) {
            this.name = name;
            this.description = description;
            this.category = category;
            this.location = location;
            this.bussinessOwnerId = bussinessOwnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessResponseBody Body;
        
        public AddBussinessResponse() {
        }
        
        public AddBussinessResponse(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddBussinessResult;
        
        public AddBussinessResponseBody() {
        }
        
        public AddBussinessResponseBody(bool AddBussinessResult) {
            this.AddBussinessResult = AddBussinessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CuponSystemWebServiceSoapChannel : UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CuponSystemWebServiceSoapClient : System.ServiceModel.ClientBase<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap>, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap {
        
        public CuponSystemWebServiceSoapClient() {
        }
        
        public CuponSystemWebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CuponSystemWebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuponSystemWebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CuponSystemWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserResponse UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AuthenticateUser(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUser(request);
        }
        
        public bool AuthenticateUser(string userName, string password) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserResponse retVal = ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AuthenticateUser(inValue);
            return retVal.Body.AuthenticateUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserResponse> UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AuthenticateUserAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequest request) {
            return base.Channel.AuthenticateUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserResponse> AuthenticateUserAsync(string userName, string password) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AuthenticateUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            return ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AuthenticateUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerResponse UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AddBussinessOwner(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequest request) {
            return base.Channel.AddBussinessOwner(request);
        }
        
        public bool AddBussinessOwner(string userName, string password, string email) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerResponse retVal = ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AddBussinessOwner(inValue);
            return retVal.Body.AddBussinessOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerResponse> UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AddBussinessOwnerAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequest request) {
            return base.Channel.AddBussinessOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerResponse> AddBussinessOwnerAsync(string userName, string password, string email) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessOwnerRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            return ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AddBussinessOwnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserResponse UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AddBasicUser(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequest request) {
            return base.Channel.AddBasicUser(request);
        }
        
        public bool AddBasicUser(string userName, string password, string email, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Gender gender, string phoneNumber, System.DateTime birthDate, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Location location) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.gender = gender;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.birthDate = birthDate;
            inValue.Body.location = location;
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserResponse retVal = ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AddBasicUser(inValue);
            return retVal.Body.AddBasicUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserResponse> UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AddBasicUserAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequest request) {
            return base.Channel.AddBasicUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserResponse> AddBasicUserAsync(string userName, string password, string email, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Gender gender, string phoneNumber, System.DateTime birthDate, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Location location) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBasicUserRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            inValue.Body.gender = gender;
            inValue.Body.phoneNumber = phoneNumber;
            inValue.Body.birthDate = birthDate;
            inValue.Body.location = location;
            return ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AddBasicUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminResponse UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AddSystemAdmin(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequest request) {
            return base.Channel.AddSystemAdmin(request);
        }
        
        public bool AddSystemAdmin(string userName, string password, string email) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminResponse retVal = ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AddSystemAdmin(inValue);
            return retVal.Body.AddSystemAdminResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminResponse> UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AddSystemAdminAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequest request) {
            return base.Channel.AddSystemAdminAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminResponse> AddSystemAdminAsync(string userName, string password, string email) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddSystemAdminRequestBody();
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.email = email;
            return ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AddSystemAdminAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessResponse UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AddBussiness(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequest request) {
            return base.Channel.AddBussiness(request);
        }
        
        public bool AddBussiness(string name, string description, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Category category, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Location location, int bussinessOwnerId) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.location = location;
            inValue.Body.bussinessOwnerId = bussinessOwnerId;
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessResponse retVal = ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AddBussiness(inValue);
            return retVal.Body.AddBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessResponse> UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap.AddBussinessAsync(UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequest request) {
            return base.Channel.AddBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessResponse> AddBussinessAsync(string name, string description, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Category category, UnitTestWebCuponSystemService.CuponSystemWebServiceReference.Location location, int bussinessOwnerId) {
            UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequest inValue = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.CuponSystemWebServiceReference.AddBussinessRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.location = location;
            inValue.Body.bussinessOwnerId = bussinessOwnerId;
            return ((UnitTestWebCuponSystemService.CuponSystemWebServiceReference.CuponSystemWebServiceSoap)(this)).AddBussinessAsync(inValue);
        }
    }
}
