//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnitTestWebCuponSystemService.BussinessServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BussinessServiceReference.BussinessServicesSoap")]
    public interface BussinessServicesSoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessResponse AddBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessResponse> AddBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessResponse DeleteBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessResponse> DeleteBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApproveBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessResponse ApproveBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ApproveBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessResponse> ApproveBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessId from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessResponse UpdateBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessResponse> UpdateBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequest request);
        
        // CODEGEN: Generating message contract since element name bussinessName from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByName", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameResponse FindBussinessByName(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByName", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameResponse> FindBussinessByNameAsync(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequest request);
        
        // CODEGEN: Generating message contract since element name ownerID from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessOfOwner", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerResponse FindBussinessOfOwner(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessOfOwner", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerResponse> FindBussinessOfOwnerAsync(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequest request);
        
        // CODEGEN: Generating message contract since element name category from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByCategory", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryResponse FindBussinessByCategory(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FindBussinessByCategory", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryResponse> FindBussinessByCategoryAsync(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequest request);
        
        // CODEGEN: Generating message contract since element name GetAllUnapprovedBussinessResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUnapprovedBussiness", ReplyAction="*")]
        UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessResponse GetAllUnapprovedBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllUnapprovedBussiness", ReplyAction="*")]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessResponse> GetAllUnapprovedBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequestBody Body;
        
        public AddBussinessRequest() {
        }
        
        public AddBussinessRequest(UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string longtitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string photo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string bussinessOwnerId;
        
        public AddBussinessRequestBody() {
        }
        
        public AddBussinessRequestBody(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            this.name = name;
            this.description = description;
            this.category = category;
            this.latitude = latitude;
            this.longtitude = longtitude;
            this.photo = photo;
            this.bussinessOwnerId = bussinessOwnerId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessResponseBody Body;
        
        public AddBussinessResponse() {
        }
        
        public AddBussinessResponse(UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool AddBussinessResult;
        
        public AddBussinessResponseBody() {
        }
        
        public AddBussinessResponseBody(bool AddBussinessResult) {
            this.AddBussinessResult = AddBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequestBody Body;
        
        public DeleteBussinessRequest() {
        }
        
        public DeleteBussinessRequest(UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessId;
        
        public DeleteBussinessRequestBody() {
        }
        
        public DeleteBussinessRequestBody(string bussinessId) {
            this.bussinessId = bussinessId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessResponseBody Body;
        
        public DeleteBussinessResponse() {
        }
        
        public DeleteBussinessResponse(UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool DeleteBussinessResult;
        
        public DeleteBussinessResponseBody() {
        }
        
        public DeleteBussinessResponseBody(bool DeleteBussinessResult) {
            this.DeleteBussinessResult = DeleteBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequestBody Body;
        
        public ApproveBussinessRequest() {
        }
        
        public ApproveBussinessRequest(UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessId;
        
        public ApproveBussinessRequestBody() {
        }
        
        public ApproveBussinessRequestBody(string bussinessId) {
            this.bussinessId = bussinessId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ApproveBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ApproveBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessResponseBody Body;
        
        public ApproveBussinessResponse() {
        }
        
        public ApproveBussinessResponse(UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ApproveBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool ApproveBussinessResult;
        
        public ApproveBussinessResponseBody() {
        }
        
        public ApproveBussinessResponseBody(bool ApproveBussinessResult) {
            this.ApproveBussinessResult = ApproveBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequestBody Body;
        
        public UpdateBussinessRequest() {
        }
        
        public UpdateBussinessRequest(UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBussinessRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string description;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string category;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string latitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string longtitude;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string photo;
        
        public UpdateBussinessRequestBody() {
        }
        
        public UpdateBussinessRequestBody(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            this.bussinessId = bussinessId;
            this.name = name;
            this.description = description;
            this.category = category;
            this.latitude = latitude;
            this.longtitude = longtitude;
            this.photo = photo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessResponseBody Body;
        
        public UpdateBussinessResponse() {
        }
        
        public UpdateBussinessResponse(UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateBussinessResult;
        
        public UpdateBussinessResponseBody() {
        }
        
        public UpdateBussinessResponseBody(bool UpdateBussinessResult) {
            this.UpdateBussinessResult = UpdateBussinessResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByNameRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByName", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequestBody Body;
        
        public FindBussinessByNameRequest() {
        }
        
        public FindBussinessByNameRequest(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByNameRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bussinessName;
        
        public FindBussinessByNameRequestBody() {
        }
        
        public FindBussinessByNameRequestBody(string bussinessName) {
            this.bussinessName = bussinessName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByNameResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByNameResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameResponseBody Body;
        
        public FindBussinessByNameResponse() {
        }
        
        public FindBussinessByNameResponse(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByNameResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessByNameResult;
        
        public FindBussinessByNameResponseBody() {
        }
        
        public FindBussinessByNameResponseBody(string FindBussinessByNameResult) {
            this.FindBussinessByNameResult = FindBussinessByNameResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessOfOwnerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessOfOwner", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequestBody Body;
        
        public FindBussinessOfOwnerRequest() {
        }
        
        public FindBussinessOfOwnerRequest(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessOfOwnerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ownerID;
        
        public FindBussinessOfOwnerRequestBody() {
        }
        
        public FindBussinessOfOwnerRequestBody(string ownerID) {
            this.ownerID = ownerID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessOfOwnerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessOfOwnerResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerResponseBody Body;
        
        public FindBussinessOfOwnerResponse() {
        }
        
        public FindBussinessOfOwnerResponse(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessOfOwnerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessOfOwnerResult;
        
        public FindBussinessOfOwnerResponseBody() {
        }
        
        public FindBussinessOfOwnerResponseBody(string FindBussinessOfOwnerResult) {
            this.FindBussinessOfOwnerResult = FindBussinessOfOwnerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByCategoryRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByCategory", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequestBody Body;
        
        public FindBussinessByCategoryRequest() {
        }
        
        public FindBussinessByCategoryRequest(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByCategoryRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string category;
        
        public FindBussinessByCategoryRequestBody() {
        }
        
        public FindBussinessByCategoryRequestBody(string category) {
            this.category = category;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindBussinessByCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindBussinessByCategoryResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryResponseBody Body;
        
        public FindBussinessByCategoryResponse() {
        }
        
        public FindBussinessByCategoryResponse(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FindBussinessByCategoryResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindBussinessByCategoryResult;
        
        public FindBussinessByCategoryResponseBody() {
        }
        
        public FindBussinessByCategoryResponseBody(string FindBussinessByCategoryResult) {
            this.FindBussinessByCategoryResult = FindBussinessByCategoryResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUnapprovedBussinessRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUnapprovedBussiness", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequestBody Body;
        
        public GetAllUnapprovedBussinessRequest() {
        }
        
        public GetAllUnapprovedBussinessRequest(UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllUnapprovedBussinessRequestBody {
        
        public GetAllUnapprovedBussinessRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllUnapprovedBussinessResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllUnapprovedBussinessResponse", Namespace="http://tempuri.org/", Order=0)]
        public UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessResponseBody Body;
        
        public GetAllUnapprovedBussinessResponse() {
        }
        
        public GetAllUnapprovedBussinessResponse(UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllUnapprovedBussinessResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetAllUnapprovedBussinessResult;
        
        public GetAllUnapprovedBussinessResponseBody() {
        }
        
        public GetAllUnapprovedBussinessResponseBody(string GetAllUnapprovedBussinessResult) {
            this.GetAllUnapprovedBussinessResult = GetAllUnapprovedBussinessResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface BussinessServicesSoapChannel : UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BussinessServicesSoapClient : System.ServiceModel.ClientBase<UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap>, UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap {
        
        public BussinessServicesSoapClient() {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BussinessServicesSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BussinessServicesSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessResponse UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.AddBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequest request) {
            return base.Channel.AddBussiness(request);
        }
        
        public bool AddBussiness(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            inValue.Body.bussinessOwnerId = bussinessOwnerId;
            UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessResponse retVal = ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).AddBussiness(inValue);
            return retVal.Body.AddBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessResponse> UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.AddBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequest request) {
            return base.Channel.AddBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessResponse> AddBussinessAsync(string name, string description, string category, string latitude, string longtitude, string photo, string bussinessOwnerId) {
            UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.AddBussinessRequestBody();
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            inValue.Body.bussinessOwnerId = bussinessOwnerId;
            return ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).AddBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessResponse UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.DeleteBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequest request) {
            return base.Channel.DeleteBussiness(request);
        }
        
        public bool DeleteBussiness(string bussinessId) {
            UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessResponse retVal = ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).DeleteBussiness(inValue);
            return retVal.Body.DeleteBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessResponse> UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.DeleteBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequest request) {
            return base.Channel.DeleteBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessResponse> DeleteBussinessAsync(string bussinessId) {
            UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.DeleteBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            return ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).DeleteBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessResponse UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.ApproveBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequest request) {
            return base.Channel.ApproveBussiness(request);
        }
        
        public bool ApproveBussiness(string bussinessId) {
            UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessResponse retVal = ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).ApproveBussiness(inValue);
            return retVal.Body.ApproveBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessResponse> UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.ApproveBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequest request) {
            return base.Channel.ApproveBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessResponse> ApproveBussinessAsync(string bussinessId) {
            UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.ApproveBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            return ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).ApproveBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessResponse UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.UpdateBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequest request) {
            return base.Channel.UpdateBussiness(request);
        }
        
        public bool UpdateBussiness(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessResponse retVal = ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).UpdateBussiness(inValue);
            return retVal.Body.UpdateBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessResponse> UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.UpdateBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequest request) {
            return base.Channel.UpdateBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessResponse> UpdateBussinessAsync(string bussinessId, string name, string description, string category, string latitude, string longtitude, string photo) {
            UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.UpdateBussinessRequestBody();
            inValue.Body.bussinessId = bussinessId;
            inValue.Body.name = name;
            inValue.Body.description = description;
            inValue.Body.category = category;
            inValue.Body.latitude = latitude;
            inValue.Body.longtitude = longtitude;
            inValue.Body.photo = photo;
            return ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).UpdateBussinessAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameResponse UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.FindBussinessByName(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequest request) {
            return base.Channel.FindBussinessByName(request);
        }
        
        public string FindBussinessByName(string bussinessName) {
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequestBody();
            inValue.Body.bussinessName = bussinessName;
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameResponse retVal = ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).FindBussinessByName(inValue);
            return retVal.Body.FindBussinessByNameResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameResponse> UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.FindBussinessByNameAsync(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequest request) {
            return base.Channel.FindBussinessByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameResponse> FindBussinessByNameAsync(string bussinessName) {
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByNameRequestBody();
            inValue.Body.bussinessName = bussinessName;
            return ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).FindBussinessByNameAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerResponse UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.FindBussinessOfOwner(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequest request) {
            return base.Channel.FindBussinessOfOwner(request);
        }
        
        public string FindBussinessOfOwner(string ownerID) {
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequestBody();
            inValue.Body.ownerID = ownerID;
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerResponse retVal = ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).FindBussinessOfOwner(inValue);
            return retVal.Body.FindBussinessOfOwnerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerResponse> UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.FindBussinessOfOwnerAsync(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequest request) {
            return base.Channel.FindBussinessOfOwnerAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerResponse> FindBussinessOfOwnerAsync(string ownerID) {
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessOfOwnerRequestBody();
            inValue.Body.ownerID = ownerID;
            return ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).FindBussinessOfOwnerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryResponse UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.FindBussinessByCategory(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequest request) {
            return base.Channel.FindBussinessByCategory(request);
        }
        
        public string FindBussinessByCategory(string category) {
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequestBody();
            inValue.Body.category = category;
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryResponse retVal = ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).FindBussinessByCategory(inValue);
            return retVal.Body.FindBussinessByCategoryResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryResponse> UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.FindBussinessByCategoryAsync(UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequest request) {
            return base.Channel.FindBussinessByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryResponse> FindBussinessByCategoryAsync(string category) {
            UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.FindBussinessByCategoryRequestBody();
            inValue.Body.category = category;
            return ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).FindBussinessByCategoryAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessResponse UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.GetAllUnapprovedBussiness(UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequest request) {
            return base.Channel.GetAllUnapprovedBussiness(request);
        }
        
        public string GetAllUnapprovedBussiness() {
            UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequestBody();
            UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessResponse retVal = ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).GetAllUnapprovedBussiness(inValue);
            return retVal.Body.GetAllUnapprovedBussinessResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessResponse> UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap.GetAllUnapprovedBussinessAsync(UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequest request) {
            return base.Channel.GetAllUnapprovedBussinessAsync(request);
        }
        
        public System.Threading.Tasks.Task<UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessResponse> GetAllUnapprovedBussinessAsync() {
            UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequest inValue = new UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequest();
            inValue.Body = new UnitTestWebCuponSystemService.BussinessServiceReference.GetAllUnapprovedBussinessRequestBody();
            return ((UnitTestWebCuponSystemService.BussinessServiceReference.BussinessServicesSoap)(this)).GetAllUnapprovedBussinessAsync(inValue);
        }
    }
}
